import React, { useState, useEffect } from 'react';
import { Cards, FormField, Loader } from '../components';

const RenderCard = ({ data, title }) => {
  if (data?.lenght > 0) {
    return data.map((post) => <Cards key={post} {...post} />)
  }

  return <h2 className="mt-5 font-bold text-[#6449ff] text-xl uppercase">{title}</h2>
}

const Home = () => {
  const [loading, setloading] = useState(false);
  const [allPost, setAllPost] = useState(null);

  const [searchText, setSearchText] = useState();

  return (

    <section className='max-w-7xl mx-auto'>
      <div>
        <h1 className='font-extrabold text-[32px] test-[#222328]'>The Community Show Case</h1>
        <p1 className='text-[16px] text-[#666e75] mt-2 max-w-[500px]'>Browse through the collection of imaginative and visually stunning images generated by WALLE- AI</p1>
      </div>

      <div className='mt-16'>
        <FormField />
      </div>

      <div className='mt-10'>
        {loading ? (
          <div className='flex justify-center item-center'>
            <Loader />
          </div>
        ) : (
          <>
            {searchText && (<h2 className='font-medium text-[#666e75] text-xl mb-3'> showing results for
              <span className='[#222328]'> {searchText}</span>
            </h2>
            )}

            <div className='grid lg:grid-cols-4 sm:grid-cols-3 xs:grid-cols-2 grid-cols-1 gap-3'>
              {searchText ? (<RenderCard data={[]} title="No Search Result Found" />
              ) : (
                <RenderCard data={[]} title="No Posts Found" />)}
            </div>
          </>
        )}
      </div>
    </section>
  )
}

export default Home